In [46]:
import pandas as pd
import numpy as np

test = pd.read_csv('test.csv')

In [47]:
test.Date = pd.to_datetime(test.Date)

In [50]:
weather_clean = pd.read_csv('weather_dt_clean.csv')

weather_clean['Date'] = pd.to_datetime(weather_clean['Date'])
weather_clean.PrecipTotal.replace(regex=True,inplace=True,to_replace=r'T',value=0.005)
weather_clean.PrecipTotal = weather_clean.PrecipTotal.astype(float)

weather_cols = ['Tmax','Tmin','Tavg','DewPoint',
                'Heat','Cool','PrecipTotal',
                'StnPressure','ResultDir','AvgSpeed']

#List of lists that will have all the 15 days prior weather data
new_cols = [weather_cols]
#iterate through every row
for i in test.index:
    new_row = [] #create a new, empty row
    #create a new datafram containing all rows that occurred 15 days before the ith row
    #and were at the same station
    fif_days_before = weather_clean[weather_clean['Date'] == (test.loc[i].Date - pd.Timedelta('15 days'))]
    #print df.loc[i].Date
    #print len(fif_days_before)
    
    for j in weather_cols:
        new_row.append(np.mean([fif_days_before.iloc[0][j], fif_days_before.iloc[1][j]]))
        
            
    new_cols.append(new_row)
	
new_col_names = [i + "-15d" for i in weather_cols]
new_cols_df = pd.DataFrame(new_cols[1:],columns=new_col_names)
dums = pd.get_dummies(test.Trap,drop_first=True)
result = pd.concat([test, new_cols_df,dums], axis=1)

In [54]:
result = test_weather.applymap(lambda x: np.nan if x == 'M' else x)

result = result['PrecipTotal'].replace(regex=True,inplace=True,to_replace=r'T',value=0.005)

In [59]:
result.columns()

AttributeError: 'NoneType' object has no attribute 'columns'

In [39]:
# result.Tavg.fillna(method='pad', inplace=True)

# test_weather.DewPoint.fillna(method='pad', inplace=True)

# test_weather.WetBulb.fillna(method='pad', inplace=True)

# test_weather.Heat.fillna(method='pad', inplace=True)

# test_weather.Cool.fillna(method='pad', inplace=True)

# test_weather.PrecipTotal.fillna(method='pad', inplace=True)

# test_weather.StnPressure.fillna(method='pad', inplace=True)

# test_weather.SeaLevel.fillna(method='pad', inplace=True)

# test_weather.AvgSpeed.fillna(method='pad', inplace=True)

In [40]:
# test_weather.drop(["Depth", "Water1", "SnowFall",'Depart', 'CodeSum', 'Sunset', 'Sunrise', 'WetBulb','ResultSpeed','SeaLevel'], inplace=True, axis=1)

In [55]:
test_weather['Heat'] = [float(x) for x in test_weather.Heat]

test_weather['Cool'] = [float(x) for x in test_weather.Cool]

test_weather['StnPressure'] = [float(x) for x in test_weather.StnPressure]

test_weather['AvgSpeed'] = [float(x) for x in test_weather.AvgSpeed]

test_weather['PrecipTotal'] = [float(x) for x in test_weather.PrecipTotal]

ValueError: could not convert string to float: T

In [44]:
# traps = ['T002', 'T007', 'T015', 'T045', 'T046', 'T048', 'T049', 'T050',
#        'T054', 'T086', 'T091', 'T094', 'T096', 'T129', 'T143', 'T148',
#        'T153', 'T159', 'T009', 'T011', 'T016', 'T019', 'T025', 'T028',
#        'T031', 'T033', 'T089', 'T090', 'T092', 'T135', 'T141', 'T142',
#        'T145', 'T146', 'T147', 'T149', 'T150', 'T151', 'T152', 'T154',
#        'T158', 'T162', 'T218', 'T220', 'T001', 'T003', 'T006', 'T008',
#        'T012', 'T034', 'T037', 'T040', 'T043', 'T047', 'T051', 'T085',
#        'T088', 'T161', 'T219', 'T013', 'T014', 'T018', 'T030', 'T084',
#        'T144', 'T160', 'T005', 'T017', 'T044', 'T095', 'T004', 'T035',
#        'T036', 'T039', 'T060', 'T061', 'T062', 'T065', 'T066', 'T067',
#        'T069', 'T070', 'T071', 'T073', 'T074', 'T075', 'T076', 'T077',
#        'T079', 'T080', 'T081', 'T082', 'T083', 'T114', 'T155', 'T063',
#        'T115', 'T138', 'T200', 'T206', 'T209', 'T212', 'T215', 'T107',
#        'T128', 'T072', 'T078', 'T097', 'T099', 'T100', 'T102', 'T103',
#        'T027', 'T156', 'T157', 'T221', 'T900', 'T903', 'T222', 'T223',
#        'T225', 'T227', 'T224', 'T226', 'T229', 'T230', 'T228', 'T232',
#        'T231', 'T235', 'T233', 'T236', 'T237', 'T238', 'T094B', 'T054C']

# def codesum_vars():
#     for i in traps:
#         test_weather[i] = test_weather['Trap'].str.contains(i,regex=True).astype(int)
# codesum_vars()

In [43]:
species = ['CULEX PIPIENS/RESTUANS', 'CULEX RESTUANS', 'CULEX PIPIENS',
       'CULEX SALINARIUS', 'CULEX TERRITANS', 'CULEX TARSALIS',
       'CULEX ERRATICUS']

def codesum_vars():
    for i in species:
        result[i] = result['Species'].str.contains(i,regex=True).astype(int)
codesum_vars()

KeyError: 'Species'

In [41]:
result.drop(['Address','Species', 'Street','Trap','AddressNumberAndStreet','AddressAccuracy'],inplace=True, axis=1)

In [48]:
result.head()

,Station,Date,Tmax,Tmin,Tavg,DewPoint,Heat,Cool,PrecipTotal,StnPressure,...,T238,T094B,T054C,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX PIPIENS,CULEX SALINARIUS,CULEX TERRITANS,CULEX TARSALIS,CULEX ERRATICUS
0,1,2008-06-11,86,61,74,56,0.0,9.0,0.0,29.28,...,0,0,0,1,0,1,0,0,0,0
1,1,2008-06-11,86,61,74,56,0.0,9.0,0.0,29.28,...,0,0,0,0,1,0,0,0,0,0
2,1,2008-06-11,86,61,74,56,0.0,9.0,0.0,29.28,...,0,0,0,0,0,1,0,0,0,0
3,1,2008-06-11,86,61,74,56,0.0,9.0,0.0,29.28,...,0,0,0,0,0,0,1,0,0,0
4,1,2008-06-11,86,61,74,56,0.0,9.0,0.0,29.28,...,0,0,0,0,0,0,0,1,0,0

In [45]:
for i in result.columns:
    print i

Id
Date
Block
Latitude
Longitude
Tmax-15d
Tmin-15d
Tavg-15d
DewPoint-15d
Heat-15d
Cool-15d
PrecipTotal-15d
StnPressure-15d
ResultDir-15d
AvgSpeed-15d
T002
T002A
T002B
T003
T004
T005
T006
T007
T008
T009
T011
T012
T013
T014
T015
T016
T017
T018
T019
T025
T027
T028
T030
T031
T033
T034
T035
T036
T037
T039
T040
T043
T044
T045
T046
T047
T048
T049
T050
T051
T054
T054C
T060
T061
T062
T063
T065
T065A
T066
T067
T069
T070
T071
T072
T073
T074
T075
T076
T077
T078
T079
T080
T081
T082
T083
T084
T085
T086
T088
T089
T090
T090A
T090B
T090C
T091
T092
T094
T094B
T095
T096
T097
T099
T100
T102
T103
T107
T114
T115
T128
T128A
T129
T135
T138
T141
T142
T143
T144
T145
T146
T147
T148
T149
T150
T151
T152
T153
T154
T155
T156
T157
T158
T159
T160
T161
T162
T200
T200A
T200B
T206
T209
T212
T215
T218
T218A
T218B
T218C
T219
T220
T221
T222
T223
T224
T225
T226
T227
T228
T229
T230
T231
T232
T233
T234
T235
T236
T237
T238
T900
T903